# Generated by Django 2.1.7 on 2019-03-14 22:25

from django.db import migrations, models
import storages.backends.s3boto
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('title', models.CharField(blank=True, max_length=256)),
                ('description', models.TextField(blank=True)),
                ('author', models.CharField(blank=True, max_length=256)),
                ('duration', models.TimeField(blank=True)),
                ('file', models.FileField(blank=True, null=True, storage=storages.backends.s3boto.S3BotoStorage(bucket='zebra-video'), upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
